[project]
name = "build-llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebook>=7.5.0",
    "tiktoken>=0.12.0",
    "torch==2.4.0",
]
